export const defaultStats: Record<TStatSection, TStat[]> = {
  landing: [
    {
      id: "happy-climbers",
      title: "Happy Climbers",
      value: "2,000+",
      description: "Successfully guided to summits",
      icon: "Users",
      order: 1,
    },
    {
      id: "mountains-conquered",
      title: "Mountains Conquered",
      value: "50+",
      description: "Across all seven continents",
      icon: "Mountain",
      order: 2,
    },
    {
      id: "successful-expeditions",
      title: "Successful Expeditions",
      value: "500+",
      description: "Completed with zero incidents",
      icon: "Award",
      order: 3,
    },
    {
      id: "years-experience",
      title: "Years Experience",
      value: "15",
      description: "In professional mountaineering",
      icon: "Award",
      order: 4,
    },
  ],
  international: [
    {
      id: "countries",
      title: "Countries",
      value: "1",
      description: "",
      icon: "Globe",
      order: 1,
    },
    {
      id: "starting-from",
      title: "Starting From",
      value: "$799+",
      description: "",
      icon: "Plane",
      order: 2,
    },
    {
      id: "global-travelers",
      title: "Global Travelers",
      value: "500+",
      description: "",
      icon: "Users",
      order: 3,
    },
  ],
  domestic: [
    {
      id: "destinations",
      title: "Destinations",
      value: "1",
      description: "",
      icon: "MapPin",
      order: 1,
    },
    {
      id: "starting-from-domestic",
      title: "Starting From",
      value: "₹5K+",
      description: "",
      icon: "Heart",
      order: 2,
    },
    {
      id: "happy-travelers",
      title: "Happy Travelers",
      value: "100+",
      description: "",
      icon: "Users",
      order: 3,
    },
  ],
};
